/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Andrea
 * Created: 7-mag-2018
 */

create table  utente {

	id INTEGER GENERATED BY DEFAULT AS IDENTITY,  /**chiave primaria della nostra tabella */
	nome VARCHAR(24),				/** incrementato automaticamente */
	cognome VARCHAR(24),
	email VARCHAR(24),unique,
	urlimageProfil VARCHAR(512),
	password VARCHAR (64),
	is_author INTEGER,
	PRIMARY KEY id
};

create table Notizia {

	id INTEGER primary GENERATED BY DEFAULT AS IDENTITY,
	titolo VARCHAR (32),unique,
	content VARCHAR (1024),
	url VARCHAR (64),
	categoria INTEGER,
	autore INTEGER REFERENCES utente (id)
};

CREATE TABLE commenti(
    id SERIAL primary key,
    id_utente BIGINT UNSIGNED REFERENCES utente(id) on delete no action 
                                                    on update cascade,
    id_articolo BIGINT UNSIGNED REFERENCES articolo(id) on delete no action 
                                                      on update cascade, 
    testo varchar(1500)
);